// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexTranscodeJob) DeepCopyInto(out *PlexTranscodeJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexTranscodeJob.
func (in *PlexTranscodeJob) DeepCopy() *PlexTranscodeJob {
	if in == nil {
		return nil
	}
	out := new(PlexTranscodeJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlexTranscodeJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexTranscodeJobList) DeepCopyInto(out *PlexTranscodeJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlexTranscodeJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexTranscodeJobList.
func (in *PlexTranscodeJobList) DeepCopy() *PlexTranscodeJobList {
	if in == nil {
		return nil
	}
	out := new(PlexTranscodeJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlexTranscodeJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexTranscodeJobSpec) DeepCopyInto(out *PlexTranscodeJobSpec) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexTranscodeJobSpec.
func (in *PlexTranscodeJobSpec) DeepCopy() *PlexTranscodeJobSpec {
	if in == nil {
		return nil
	}
	out := new(PlexTranscodeJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlexTranscodeJobStatus) DeepCopyInto(out *PlexTranscodeJobStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlexTranscodeJobStatus.
func (in *PlexTranscodeJobStatus) DeepCopy() *PlexTranscodeJobStatus {
	if in == nil {
		return nil
	}
	out := new(PlexTranscodeJobStatus)
	in.DeepCopyInto(out)
	return out
}
